### ISSUE TITLE
update GISAID acknowledgment table

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/SARS-CoV-2-RBD_MAP_clinical_Abs#16]
@ajgreaney, I'm wondering if we could ask you to do this for clinical antibodies paper:

In #15 we have updated to latest (Jan-11-2021) GISAID mutation frequencies. Can you update / fix the GISAID acknowledgements table to represent that? I figured you might have the easiest time doing this as you've done it recently. After that is done and merged, can you also ensure any link to this table in manuscript is accurate?

**Comment by ajgreaney** [comment]
Yes, I will work on this. If I don't finish it tonight, I should be able to tomorrow.

**Comment by jbloom** [comment]
Addressed in #15
